version: '3.5'

networks:
  imgresizer:
    driver: bridge
    
services:
  rabbitmq:
    container_name: rabbitmq
    image: library/rabbitmq:3.8.3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - imgresizer
    restart: unless-stopped

  api:
    container_name: api
    build: api
    environment:
      RABBITMQ_HOST: rabbitmq
      PYTHONUNBUFFERED: 1
    ports:
      - 5000:5000
    networks:
      - imgresizer
    depends_on:
      - rabbitmq
    restart: unless-stopped

  resizer:
    container_name: resizer
    build: resizer
    environment:
      RABBITMQ_HOST: rabbitmq
      PYTHONUNBUFFERED: 1 
    networks:
      - imgresizer
    depends_on:
      - rabbitmq
    restart: unless-stopped

